url: "http://limoges.afup.org"

title: "AFUP Limoges"
description: >-
  Antenne AFUP sur Limoges
twitter_username: AFUP_Limoges
meetup_url: "https://www.meetup.com/fr-FR/afup-limoges-php"

permalink: /posts/:title

ga_ua: "G-RECL2R0BHD"
home_featured_articles_count: 1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Makefile
   - docker-compose.yml
   - docker-compose.override.yml-dist
   - docker-compose.override.yml
   - Gemfile
   - Gemfile.lock

feed:
  path: feed
